-- PostgreSQL only. Execute once against an empty application schema.
-- This file owns its transaction; do not wrap it in another transaction runner.
BEGIN;

CREATE TABLE schema_migrations (
    version bigint PRIMARY KEY,
    applied_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO schema_migrations (version) VALUES (1);

CREATE TABLE merchant (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(64) NOT NULL,
    name varchar(128) NOT NULL,
    website_url varchar(2048) NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_merchant_code UNIQUE (code),
    CONSTRAINT ck_merchant_code CHECK (code ~ '^[a-z0-9][a-z0-9_-]{0,63}$'),
    CONSTRAINT ck_merchant_name CHECK (char_length(btrim(name)) > 0)
);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(32) NOT NULL,
    nickname varchar(64) NOT NULL,
    password_hash varchar(255) NOT NULL,
    role varchar(16) NOT NULL DEFAULT 'user',
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT ck_users_username CHECK (username ~ '^[a-z0-9_]{4,32}$'),
    CONSTRAINT ck_users_nickname CHECK (char_length(btrim(nickname)) BETWEEN 1 AND 32),
    CONSTRAINT ck_users_role CHECK (role IN ('user', 'admin'))
);
CREATE INDEX idx_users_role_enabled ON users (role, enabled, id);

CREATE TABLE vps_detail (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id bigint NOT NULL REFERENCES merchant(id) ON DELETE RESTRICT,
    code varchar(64) NOT NULL,
    name varchar(128) NOT NULL,
    description text NOT NULL DEFAULT '',
    cpu_cores integer NOT NULL,
    memory_mb integer NOT NULL,
    disk_gb integer NOT NULL,
    disk_type varchar(16) NOT NULL,
    transfer_gb integer,
    port_mbps integer,
    price_amount numeric(12,2) NOT NULL,
    currency char(3) NOT NULL,
    billing_period varchar(16) NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_vps_merchant_code UNIQUE (merchant_id, code),
    CONSTRAINT ck_vps_code CHECK (code ~ '^[a-z0-9][a-z0-9_-]{0,63}$'),
    CONSTRAINT ck_vps_name CHECK (char_length(btrim(name)) > 0),
    CONSTRAINT ck_vps_description CHECK (char_length(description) <= 10000),
    CONSTRAINT ck_vps_specs CHECK (cpu_cores > 0 AND memory_mb > 0 AND disk_gb > 0),
    CONSTRAINT ck_vps_disk_type CHECK (disk_type IN ('ssd','nvme','hdd','unknown')),
    CONSTRAINT ck_vps_transfer CHECK (transfer_gb IS NULL OR transfer_gb >= 0),
    CONSTRAINT ck_vps_port CHECK (port_mbps IS NULL OR port_mbps > 0),
    CONSTRAINT ck_vps_price CHECK (price_amount >= 0),
    CONSTRAINT ck_vps_currency CHECK (currency ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_vps_period CHECK (billing_period IN ('monthly','quarterly','yearly','one_time'))
);
CREATE INDEX idx_vps_visible ON vps_detail (merchant_id, enabled, id);

CREATE TABLE user_sessions (
    id varchar(36) PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    refresh_jti_hash char(64) NOT NULL,
    refresh_expires_at timestamptz NOT NULL,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_sessions_hash CHECK (refresh_jti_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_sessions_expiry CHECK (refresh_expires_at > created_at)
);
CREATE INDEX idx_sessions_user ON user_sessions (user_id, revoked_at);
CREATE INDEX idx_sessions_expiry ON user_sessions (refresh_expires_at);

CREATE TABLE vps_monitor_configs (
    vps_id bigint PRIMARY KEY REFERENCES vps_detail(id) ON DELETE RESTRICT,
    source_url varchar(2048) NOT NULL,
    collector_code varchar(64) NOT NULL,
    poll_interval_seconds integer NOT NULL DEFAULT 300,
    timeout_seconds integer NOT NULL DEFAULT 15,
    enabled boolean NOT NULL DEFAULT false,
    next_check_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lease_token varchar(36),
    lease_expires_at timestamptz,
    config_version bigint NOT NULL DEFAULT 1,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_monitor_interval CHECK (poll_interval_seconds BETWEEN 60 AND 86400),
    CONSTRAINT ck_monitor_timeout CHECK (timeout_seconds BETWEEN 1 AND 60 AND timeout_seconds < poll_interval_seconds),
    CONSTRAINT ck_monitor_version CHECK (config_version > 0),
    CONSTRAINT ck_monitor_lease CHECK ((lease_token IS NULL) = (lease_expires_at IS NULL))
);
CREATE INDEX idx_monitor_due ON vps_monitor_configs (enabled, next_check_at);

CREATE TABLE vps_stocks (
    vps_id bigint PRIMARY KEY REFERENCES vps_detail(id) ON DELETE RESTRICT,
    status smallint NOT NULL DEFAULT 3,
    quantity integer,
    last_checked_at timestamptz,
    last_in_stock_at timestamptz,
    last_error_code varchar(64),
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_stock_status CHECK (status IN (1,2,3)),
    CONSTRAINT ck_stock_quantity CHECK (
        (status = 1 AND (quantity IS NULL OR quantity > 0))
        OR (status = 2 AND quantity IS NOT NULL AND quantity = 0)
        OR (status = 3 AND quantity IS NULL)
    ),
    CONSTRAINT ck_stock_checked CHECK (status = 3 OR last_checked_at IS NOT NULL),
    CONSTRAINT ck_stock_in_stock CHECK (status <> 1 OR last_in_stock_at IS NOT NULL),
    CONSTRAINT ck_stock_time CHECK (
        last_in_stock_at IS NULL
        OR (last_checked_at IS NOT NULL AND last_in_stock_at <= last_checked_at)
    ),
    CONSTRAINT ck_stock_error CHECK (last_error_code IS NULL OR status = 3)
);
CREATE INDEX idx_stock_status ON vps_stocks (status, vps_id);

CREATE TABLE comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vps_id bigint NOT NULL REFERENCES vps_detail(id) ON DELETE RESTRICT,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    user_nickname varchar(64) NOT NULL,
    content text NOT NULL,
    is_anonymous boolean NOT NULL DEFAULT false,
    visibility smallint NOT NULL DEFAULT 1,
    parent_id bigint,
    root_id bigint,
    depth smallint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_comments_id_vps UNIQUE (id, vps_id),
    CONSTRAINT fk_comments_parent FOREIGN KEY (parent_id, vps_id)
        REFERENCES comments(id, vps_id) ON DELETE RESTRICT,
    CONSTRAINT fk_comments_root FOREIGN KEY (root_id, vps_id)
        REFERENCES comments(id, vps_id) ON DELETE RESTRICT,
    CONSTRAINT ck_comments_visibility CHECK (visibility IN (1,2,3,4)),
    CONSTRAINT ck_comments_content CHECK (
        (visibility = 4 AND content = '')
        OR (visibility <> 4 AND char_length(btrim(content)) BETWEEN 1 AND 2000)
    ),
    CONSTRAINT ck_comments_shape CHECK (
        (parent_id IS NULL AND root_id IS NULL AND depth = 0)
        OR (parent_id IS NOT NULL AND root_id IS NOT NULL AND depth BETWEEN 1 AND 4)
    ),
    CONSTRAINT ck_comments_not_self CHECK (
        (parent_id IS NULL OR parent_id <> id)
        AND (root_id IS NULL OR root_id <> id)
    )
);
CREATE INDEX idx_comments_parent ON comments (vps_id, parent_id, visibility, created_at, id);
CREATE INDEX idx_comments_root ON comments (vps_id, root_id, created_at, id);
CREATE INDEX idx_comments_user ON comments (user_id, created_at, id);
CREATE INDEX idx_comments_review ON comments (visibility, created_at, id);

CREATE TABLE site_settings (
    key varchar(64) PRIMARY KEY,
    value text NOT NULL,
    updated_by bigint REFERENCES users(id) ON DELETE RESTRICT,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_settings_key CHECK (key IN (
        'site_name','registration_enabled','comments_enabled',
        'anonymous_comments_enabled','comment_review_required','comment_max_depth'
    )),
    CONSTRAINT ck_settings_value CHECK (
        (key = 'site_name' AND char_length(btrim(value)) BETWEEN 1 AND 64)
        OR (key = 'comment_max_depth' AND value IN ('0','1','2','3','4'))
        OR (key IN ('registration_enabled','comments_enabled',
            'anonymous_comments_enabled','comment_review_required') AND value IN ('true','false'))
    )
);

INSERT INTO site_settings (key,value) VALUES
    ('site_name','VPS 库存监控'),
    ('registration_enabled','true'),
    ('comments_enabled','true'),
    ('anonymous_comments_enabled','true'),
    ('comment_review_required','false'),
    ('comment_max_depth','4');

COMMIT;
